import { RAZORPAY_KEY_ID, STORE_DETAILS } from "./razorpay-config.js";
window.RAZORPAY_KEY_ID = RAZORPAY_KEY_ID;
window.RAZORPAY_CONFIGURED = RAZORPAY_KEY_ID && !RAZORPAY_KEY_ID.includes("PASTE_YOUR");
window.STORE_DETAILS = STORE_DETAILS;
